apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-django
  labels:
    app: {{ .Release.Name }}-django
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-django
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-django
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000", "--insecure"]
          
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          
          