apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.djangoApp.name }}"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "{{ .Values.djangoApp.repoURL }}"
    targetRevision: "{{ .Values.djangoApp.targetRevision }}"
    path: "{{ .Values.djangoApp.path }}"

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .Values.djangoApp.namespace }}"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
