# {{- range .Values.repositories }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .name }}-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   type: git
#   url: {{ .url }}
#   {{- if .username }}
#   username: {{ .username }}
#   password: {{ .password }}
#   {{- end }}
# {{- end }}
